name: sos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  
  flutter:
dependencies:
  flutter:
    sdk: flutter
  telephony: ^0.2.0
  geolocator: ^9.0.2
  image_picker: ^1.0.7
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.5
  record: ^5.0.7
  shake: ^2.2.0
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
